# Generated by Django 5.1.5 on 2026-03-18 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Bizning ta'minotchidan qarzdorligimiz",
                        max_digits=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subcategories",
                        to="warehouse.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("dona", "Dona"),
                            ("kg", "Kilogramm"),
                            ("m2", "Kvadrat metr"),
                            ("m3", "Kub metr"),
                            ("metr", "Metr"),
                            ("qop", "Qop"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("size", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("selling_price", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "stock",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "min_stock_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=5,
                        help_text="Ogohlantirish uchun minimal miqdor",
                        max_digits=15,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="warehouse.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "new_purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "old_selling_price",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "new_selling_price",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="warehouse.productvariant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audit_date", models.DateTimeField(auto_now_add=True)),
                ("system_stock", models.DecimalField(decimal_places=2, max_digits=15)),
                ("actual_stock", models.DecimalField(decimal_places=2, max_digits=15)),
                ("difference", models.DecimalField(decimal_places=2, max_digits=15)),
                ("reason", models.TextField(blank=True)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.productvariant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("IN", "Kirim"),
                            ("OUT", "Chiqim"),
                            ("RETURN", "Qaytarildi"),
                            ("ADJUST", "Tuzatish"),
                        ],
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.productvariant",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="warehouse.supplier",
                    ),
                ),
            ],
        ),
    ]
