# Generated by Django 5.1.5 on 2026-03-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricehistory",
            name="new_purchase_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="Yangi kirim narxi"
            ),
        ),
        migrations.AlterField(
            model_name="pricehistory",
            name="new_selling_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="Yangi sotish narxi"
            ),
        ),
        migrations.AlterField(
            model_name="pricehistory",
            name="old_purchase_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="Eski kirim narxi"
            ),
        ),
        migrations.AlterField(
            model_name="pricehistory",
            name="old_selling_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="Eski sotish narxi"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Mahsulot nomi"),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[
                    ("dona", "Dona"),
                    ("kg", "Kilogramm"),
                    ("m2", "Kvadrat metr"),
                    ("m3", "Kub metr"),
                    ("metr", "Metr"),
                    ("qop", "Qop"),
                ],
                max_length=10,
                verbose_name="O'lchov birligi",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="brand",
            field=models.CharField(
                max_length=100, verbose_name="Zavod yoki Brand nomi"
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="min_stock_limit",
            field=models.DecimalField(
                decimal_places=2,
                default=5,
                help_text="Ogohlantirish uchun minimal miqdor",
                max_digits=15,
                verbose_name="Minimal qoldiq",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="purchase_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="Kirim narxi"
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="selling_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="Sotish narxi"
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="size",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="O'lchami"
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="stock",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="Qoldiq"
            ),
        ),
    ]
