# Generated by Django 5.1.5 on 2026-03-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0002_alter_pricehistory_new_purchase_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/", verbose_name="Asosiy rasm"
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="variants/",
                verbose_name="Variant rasmi",
            ),
        ),
    ]
