# Generated by Django 5.1.5 on 2026-03-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0003_product_image_productvariant_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="embedding",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Vektorli ma'lumot"
            ),
        ),
    ]
