# Generated by Django 5.1.5 on 2026-04-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0004_productvariant_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Sotuvda bormi?"),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="purchase_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="Kirim narxi",
            ),
        ),
    ]
