# Generated by Django 5.1.5 on 2025-10-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bot", "0012_remove_telegramuser_best_streak_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Kompaniya haqida matnli ma'lumot."),
                ),
            ],
        ),
    ]
