# Generated by Django 5.1.5 on 2025-10-15 15:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bot", "0013_companydata"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydata",
            name="embedding",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(), blank=True, null=True, size=None
            ),
        ),
    ]
