# Generated by Django 5.1.5 on 2025-10-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bot", "0014_companydata_embedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companydata",
            name="embedding",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
