# Generated by Django 5.1.5 on 2025-10-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bot", "0015_alter_companydata_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[("yolovchi", "Yo'lo'vchi"), ("haydovchi", "Haydovchi")],
                default=None,
                max_length=50,
                null=True,
                verbose_name="User Type",
            ),
        ),
    ]
