# Generated by Django 5.1.5 on 2026-02-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bot", "0016_telegramuser_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramuser",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[("mutaxasis", "Mutaxasis"), ("fuqaro", "Fuqaro")],
                default=None,
                max_length=50,
                null=True,
                verbose_name="User Type",
            ),
        ),
    ]
