# Generated by Django 5.1.5 on 2026-02-17 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bot", "0018_chatmessage_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Atir nomi")),
                ("brand", models.CharField(max_length=100, verbose_name="Brend")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("men", "Erkaklar uchun"),
                            ("women", "Ayollar uchun"),
                            ("unisex", "Unisex (Erkak va Ayol)"),
                        ],
                        default="unisex",
                        max_length=10,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Tavsif / Akkordlar"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Sotuvda bor"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Katalog mahsuloti",
                "verbose_name_plural": "Katalog mahsulotlari",
                "ordering": ["brand", "name"],
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Buyurtma", "verbose_name_plural": "Buyurtmalar"},
        ),
        migrations.RemoveField(
            model_name="order",
            name="product_name",
        ),
        migrations.AddField(
            model_name="order",
            name="original_price",
            field=models.DecimalField(
                decimal_places=0, default=500, max_digits=10, verbose_name="Asl narxi"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="package_type",
            field=models.CharField(
                choices=[
                    ("5_set", "5 ta (10ml) premium qutida"),
                    ("10_set", "10 ta (10ml) premium qutida"),
                ],
                default=1,
                max_length=20,
                verbose_name="Nabor turi",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                decimal_places=0,
                default=4000,
                max_digits=10,
                verbose_name="Sotuv narxi (Chegirmada)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.TextField(verbose_name="Manzil"),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="Telefon"),
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Soni"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="Bot.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="Bot.product",
                    ),
                ),
            ],
        ),
    ]
