# Generated by Django 5.1.5 on 2026-02-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bot", "0020_cart_selecteditem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegramuser",
            name="access_token",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="refresh_token",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="user_type",
        ),
        migrations.AddField(
            model_name="selecteditem",
            name="is_selected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Manzil"),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Telefon"
            ),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="state",
            field=models.CharField(
                default="START", max_length=50, verbose_name="Bot State"
            ),
        ),
    ]
