# Generated by Django 5.1.5 on 2026-03-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bot", "0021_remove_telegramuser_access_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("model", "AI"), ("admin", "Admin")],
                max_length=10,
                verbose_name="Xabar roli",
            ),
        ),
    ]
